package com.example.toneforge.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Service;

import com.example.toneforge.model.ConversionRequest;
import com.example.toneforge.model.ConversionResult;
import com.example.toneforge.strategy.AbstractLingo;
import com.example.toneforge.strategy.LingoRegistry;
import com.example.toneforge.util.Clogger;
import com.google.genai.Client;
import com.google.genai.types.GenerateContentConfig;

@Service
public class ConversionService 
{
    public static final int MAX_INPUT_LENGTH = 5000; // max characters allowed in input text
    private static final String MODEL_NAME = "models/gemini-2.5-flash";

    private final Client client;

    public ConversionService(Client client) 
    {
        this.client = client;
    }

    public ConversionResult convertText(ConversionRequest request) 
    {
        ConversionResult result = new ConversionResult();

        // === INPUT VALIDATION ===

        if (request.getText() == null || request.getText().isBlank())
        {
            result.setError("Input text cannot be empty");
            return result;
        }

        if (request.getStrategy() == null || request.getStrategy().isBlank()) 
        {
            result.setError("Strategy is required");
            return result;
        }

        AbstractLingo strategy = (AbstractLingo) LingoRegistry.fromName(request.getStrategy());
        if (strategy == null) 
        {
            result.setError("Unknown strategy: " + request.getStrategy() + ". Use /api/strategies to see available options.");
            return result;
        }

        if (request.getText().length() > MAX_INPUT_LENGTH) 
        {
            result.setError("Input text exceeds maximum length of " + MAX_INPUT_LENGTH + " characters.");
            return result;
        }

        // === CONVERSION ===
        var config = GenerateContentConfig.builder()
            .systemInstruction(strategy.getInstructions())
            .build();

        try
        {
            var response = client.models.generateContent(MODEL_NAME, request.getText(), config);

            if (response == null)
            {
                result.setError("No response from language model");
                return result;
            }

            if (response.promptFeedback().isPresent())
            {
                var feedback = response.promptFeedback().get();
                if (feedback.blockReason().isPresent())
                {
                    result.setError("Request blocked by model: " + feedback.blockReason().get());
                    return result;
                }
            }

            if (response.candidates().isEmpty() || response.candidates().get().isEmpty())
            {
                result.setError("No content generated by the model");
                return result;
            }

            var candidate = response.candidates().get().get(0);

            if (candidate.finishReason().isPresent())
            {
                switch (candidate.finishReason().get().knownEnum())
                {
                    case SAFETY      -> { result.setError("Response blocked by safety filter."); return result; }
                    case RECITATION  -> { result.setError("Response blocked due to recitation policy."); return result; }
                    case MAX_TOKENS  -> Clogger.warn("Response may be truncated — hit token limit.");
                    case STOP        -> { /* normal, continue */ }
                    default          -> Clogger.warn("Unexpected finish reason: " + candidate.finishReason().get());
                }
            }

            var content = candidate.content();
            if (content.isEmpty() || content.get().parts().isEmpty() || content.get().parts().get().isEmpty())
            {
                result.setError("Model returned an empty response.");
                return result;
            }

            String text = response.text();
            if (text == null || text.isBlank())
            {
                result.setError("Model returned an empty response.");
                return result;
            }

            result.setConvertedText(text);
        }
        catch (Exception e) 
        {
            Clogger.error("Conversion failed: " + e.getMessage());
            result.setError("Conversion failed: " + e.getMessage());
            return result;
        }

        return result;
    }

    public List<String> getAvailableStrategies() 
    {
        List<String> names = new ArrayList<>();
        for (LingoRegistry strategy : LingoRegistry.values()) names.add(strategy.name());
        return names;
    }
}